import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const {getAllBlogPosts} = require('@docusaurus/plugin-content-blog');

const sidebars: SidebarsConfig = {
        docsSidebar: [
            {type: 'autogenerated', dirName: '.'},
            {type: 'html', value: '<hr class="mt-3 mb-3"/>'},
            {type: 'link', href: 'https://github.com/BFBAN/exterior-design', label: 'BFBAN Exterior Design'},
            {type: 'link', href: `/docs/development/test-app-link`, label: 'BFBAN APP Test Links'},
            {type: 'html', value: '<hr class="mt-3 mb-3"/>'},
            {
                type: 'html',
                value: '<div style="margin: 0 10px"><span style="opacity: .6; font-size: 12px; margin-bottom: 4px">BFBAN APP docs</span><br/><img src="https://github.com/BFBAN/exterior-design/blob/main/Materials/friendly-web.png?raw=true" width="100px" /></div>'
            }
        ],
        blogSidebar: [
            {type: 'html', value: '<hr class="mt-3 mb-3"/>'},
            {
                type: 'html',
                value: '<div style="margin: 0 10px"><span style="opacity: .6; font-size: 12px; margin-bottom: 4px">BFBAN APP docs</span><br/><img src="https://github.com/BFBAN/exterior-design/blob/main/Materials/friendly-web.png?raw=true" width="100px" /></div>'
            }
        ],
    }
;

export default sidebars;
