import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const {getAllBlogPosts} = require('@docusaurus/plugin-content-blog');

const sidebars: SidebarsConfig = {
        docsSidebar: [
            {type: 'autogenerated', dirName: '.'},
            {type: 'html', value: '<hr class="mt-1 mb-1"/>'},
            {type: 'link', href: 'https://github.com/BFBAN/exterior-design', label: 'bfban-exterior-design'},
            {type: 'html', value: '<hr class="mt-1 mb-1"/>'},
            {
                type: 'html',
                value: '<div style="margin: 0 10px"><span style="opacity: .6; font-size: 12px; margin-bottom: 4px">BFBAN APP docs</span><br/><img src="https://github.com/BFBAN/exterior-design/blob/main/Materials/friendly-web.png?raw=true" width="100px" /></div>'
            }
        ],
        blogSidebar: [
            {type: 'html', value: '<hr class="mt-1 mb-1"/>'},
            {
                type: 'html',
                value: '<div style="margin: 0 10px"><span style="opacity: .6; font-size: 12px; margin-bottom: 4px">BFBAN APP docs</span><br/><img src="https://github.com/BFBAN/exterior-design/blob/main/Materials/friendly-web.png?raw=true" width="100px" /></div>'
            }
            // {
            //     type: 'category',
            //     label: 'Blog',
            //     items: getAllBlogPosts().sort((a, b) => {
            //             let start = new Date(b.metadata.date).getTime(),
            //                 end = new Date(a.metadata.date).getTime();
            //             return start - end;
            //         }
            //     ),
            // },
        ],
    }
;

export default sidebars;
