import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    tutorialSidebar: [
        {type: 'autogenerated', dirName: '.'},
        {type: 'html', value: '<hr class="mt-1 mb-1"/>'},
        {type: 'link', href: 'https://github.com/BFBAN/exterior-design', label: 'bfban-exterior-design'},
        {type: 'html', value: '<hr class="mt-1 mb-1"/>'},
        {type: 'html', value: '<div style="margin: 0 10px"><span style="opacity: .6; font-size: 12px; margin-bottom: 4px">BFBAN APP docs</span><br/><img src="https://github.com/BFBAN/exterior-design/blob/main/Materials/friendly-web.png?raw=true" width="100px" /></div>'}
    ],
};

export default sidebars;
